faceapp/urls.py
# faceapp.urls
from django.urls import path

from .apis import FaceCompare

urlpatterns = [
    path('compare/', FaceCompare.as_view(), name='face_compare'),
]

ocr_project/urls.py
# ocr_project/urls.py
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from django.contrib import admin
from django.urls import include, path  # new

urlpatterns = [
    path('admin12djfdj@/', admin.site.urls),
    path('apiImageToText/', include('reading_app.urls')),
    path('apiNurazDigitCanvas/', include('single_digit_canvas.urls')),
    path('apiHCR/', include('digit_recognizer.urls')),
    path('face/', include('faceapp.urls')),
    path('', include('nid2text.urls')),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nid2text/models.py
from django.db import models


class NIDCardStorageModel(models.Model):
    """
    store NID card images.
    """

    image = models.ImageField(upload_to='nid_cards/')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

reading_app/models.py
from django.db import models


# model for webview
class ImageUpload(models.Model):
    """
    Store requested image and image text from webview
    """

    lang_choice = (
        ('ben', 'Bangla'),
        ('eng', 'English'),
        ('ben+eng', 'Bangla & English'),
    )
    image = models.ImageField(upload_to='images_ocr_web/')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    # language=models.CharField(max_length=20,choices=lang_choice,default='bangla')
    language = models.CharField(max_length=20, choices=lang_choice, default='ben')

    class Meta:
        ordering = ('-created',)


# model for api
class UploadImage(models.Model):
    """
    Store API reuested image and Image Text
    """

    lang_choice = (
        ('ben', 'Bangla'),
        ('eng', 'English'),
        ('ben+eng', 'Bangla & English'),
    )
    image = models.ImageField(upload_to='images_ocr_api/')
    text = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    language = models.CharField(max_length=20, choices=lang_choice, default='ben')

    class Meta:
        ordering = ('-created',)

templates/home.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">

    <title>ocr</title>

  
</head>
<body style="background-image: url('media/images/bg.jpg')">
<div class="container bg-light p-5 ">
<section id="current_image" class="m-2">
    
        <h2 class="bg-info text-white text-center p-3 mb-2" >Multilingual Optical Charecter Recognition</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button id="upload" class="btn btn-primary" type="submit">Upload Image</button>
            <button id="test" class="btn btn-info" style="display: none;" >Process Image</button>
        </form>
        
        
    
</section>
{% if up_msg %}
<section id="all_img">
<div class="read " >
   
<div class="row">


     <div class="col-md-6">
         
         <img class="img-fluid" src="../media/{{current_img.image}}">
     </div>
     <div class="col-md-6">
         <textarea id="" name="" rows="18" cols="35">
            {{current_img.text}}
            </textarea>
     </div>

     

</div>
</div>
    
</section>
{% endif %}


</div>
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

</script>

</body>
</html>

templates/i2tnid.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>NID</title>
    <style>
    html, body {
        height:100%;
        width:100%;
        background-color: #FAF9F6;
    }
    .nid-form {
        width: 400px;
        margin: 50px auto;
        font-size: 15px;
    }
    .input {
        background-color: #fff;
    }
    .output {
        margin-top: 20px;
        margin-left: 170px;
        background-color: #fff;
    }
    .message {
    width: 250px;
    padding: 5px;
    color: #fff;
    border-radius: 5px;
    }
    </style>
</head>
<body>
   <div class="container h-100">
       <div class="row h-100" >
           <div class="col-2"></div>
           <div class="col-8">
                <div class="nid-form input">
                    <h3>NID Image To Text Conveter</h3> 
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <p><label for="id_language">Language:</label>
                                <select class="form-control" name="language" id="id_language">
                                    <option value="ben">Bangla</option>
                                    <option value="eng">English</option>
                                    <option value="ben+eng" selected>Bangla &amp; English</option>
                                </select>
                            </p>

                        </div>
                        <div class="form-group">
                            <p class="mb-3"><label for="id_image">Image:</label> <input class="form-control" type="file" name="image" accept="image/*" required id="id_image" style="border:none;"></p>
                        </div>
                        <button type="submit" class="btn btn-success">upload</button>
                    </form>
                </div>
                <div class="text-left output">
                    {% if display is True %}
                        {% if not_matching_object > 6 %}
                            <h3 class="bg-danger message">আরও স্পষ্ট ছবি দিন</h3>
                        {% endif %}

                        <p>{{response.header1}}</p>
                        <p>{{response.header2}}</p>
                        <p>{{response.header3}}</p>
                        <p></p>
                        <p>{{response.name_bng}}</p>
                        <p>{{response.name_eng}}</p>
                        <p>{{response.father_name}}</p>
                        <p>{{response.mother_name}}</p>
                        <p></p>
                        <p>{{response.date_of_birth}}</p>
                        <p>{{response.id_no}}</p>
                        <p></p>
                        <p>{{response.footer1}}</p>
                        <p>{{response.footer2}}</p>
                        <p></p>
                        <p>{{response.footer3}}</p>
                        <p>{{response.footer4}}</p>
                    {% endif %}
                </div>
           </div>
           <div class="col-2"></div>
       </div>
   </div>
</body>
</html>